### ISSUE TITLE
Spikes don't deal damage on rotated tips

### ISSUE THREAD

**Issue by toastertim** [toastertim/spike_mod#4]
When rotated a cardinal direction, spikes don't do damage when hit straight on the tip. Only when touched sideways or stepped up on via the "stair effect".

**Comment by Shadows-of-Fire** [comment]
Yeah, well, this is stupid, this is because minecraft only runs onCollidedWithBlock if you are actually *inside* that block space, not touching it.  But apparently 0.05 pixels is enough for it to care.
